dedis/dela

blockchain/roster.go, blockchain/skipchain/block.go, blockchain/skipchain/block_test.go, blockchain/skipchain/handler.go, blockchain/skipchain/mod.go, blockchain/skipchain/validator.go, cosi/blscosi/mod.go, crypto/bls/mod.go, crypto/mod.go, encoding/errors.go, encoding/mod.go, mod.go
This aims to add unit test to the skipchain module. This is a first wave before extracting the consensus module logic. After that the final coverage will be done.
=> Skipchain unit tests

blockchain/skipchain/db.go, blockchain/skipchain/db_test.go, blockchain/skipchain/handler_test.go, blockchain/skipchain/mod_test.go, blockchain/skipchain/validator.go, blockchain/skipchain/validator_test.go
This implements an atomic commit so that the upper layer can fail without the block to be written in the database.
=> Skipchain: atomic commit

blockchain/skipchain/mod.go, blockchain/skipchain/mod_test.go, consensus/cosipbft/mod.go, consensus/cosipbft/mod_test.go, consensus/qsc/broadcast.go, consensus/qsc/broadcast_test.go, cosi/flatcosi/mod.go, cosi/flatcosi/mod_test.go, cosi/mod.go, mino/minoch/rpc.go, mino/minoch/rpc_test.go, mino/minogrpc/server.go, mino/minogrpc/server_test.go, mino/mod.go
This adds a context to the Call function such that the caller can cancel the request if necessary.
=> RPC: add a context for cancellation

blockchain/skipchain/mod.go, blockchain/skipchain/mod_test.go, blockchain/skipchain/ops_test.go, consensus/cosipbft/mod.go, consensus/cosipbft/mod_test.go, consensus/qsc/broadcast.go, consensus/qsc/broadcast_test.go, consensus/qsc/mod.go, cosi/flatcosi/handler_test.go, cosi/flatcosi/mod.go, cosi/flatcosi/mod_test.go, cosi/threshold/actor_test.go, dkg/pedersen/mod_test.go, internal/testing/fake/mod.go, mino/gossip/flat.go, mino/gossip/flat_test.go, mino/minoch/rpc.go, mino/minoch/rpc_test.go, mino/minogrpc/rpc.go, mino/minogrpc/rpc_test.go, mino/mod.go, mino/response.go, mino/response_test.go
This fix the potential issue that occurs when an error is returned and the response channel is closed. The change makes sure that every error is read before closing.
=> Mino: fix sync of responses and errors with Call

consensus/cosipbft/types/queue_test.go, consensus/viewchange/mod.go, consensus/viewchange/roster/changeset.go, core/execution/baremetal/mod.go, core/execution/baremetal/mod_test.go, core/execution/baremetal/viewchange/mod.go, core/execution/baremetal/viewchange/mod_test.go, core/ordering/cosipbft/blockstore/mem_test.go, core/ordering/cosipbft/blocksync/default_test.go, core/ordering/cosipbft/blocksync/types/mod_test.go, core/ordering/cosipbft/json/link.go, core/ordering/cosipbft/json/mod.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/ordering/cosipbft/pbft/mod.go, core/ordering/cosipbft/pbft/mod_test.go, core/ordering/cosipbft/proc.go, core/ordering/cosipbft/proc_test.go, core/ordering/cosipbft/types/block.go, core/ordering/cosipbft/types/block_test.go, core/ordering/cosipbft/types/messages.go, core/ordering/cosipbft/types/messages_test.go, core/ordering/cosipbft/types/mod.go, core/ordering/pow/mod_test.go
This adds an execution service to change the roster through transactions.
=> Core: view change as a transaction

cli/node/memcoin/mod_test.go, core/ordering/cosipbft/json/link.go, core/ordering/cosipbft/json/link_test.go, core/ordering/cosipbft/json/mod.go, core/ordering/cosipbft/json/mod_test.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/ordering/cosipbft/pbft/mod.go, core/ordering/cosipbft/pbft/mod_test.go, core/ordering/cosipbft/pbft/view.go, core/ordering/cosipbft/pbft/view_test.go, core/ordering/cosipbft/proc.go, core/ordering/cosipbft/proc_test.go, core/ordering/cosipbft/types/chain.go, core/ordering/cosipbft/types/messages.go, core/ordering/cosipbft/types/messages_test.go
This adds a signature to view messages so that it can be verified that a node asked for a view change.
Also: add view messages when sending a proposed block if the leader comes from a view change so that nodes can catch up if necessary.
=> Core: pbft view are now signed

core/ordering/cosipbft/blockstore/mod.go, core/ordering/cosipbft/blockstore/tree.go, core/ordering/cosipbft/blockstore/tree_test.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/ordering/cosipbft/pbft/mod.go
This fixes an issue with timeouts in the test and it also fixes a rare issue where the proof can be unsync between the tree and the latest block.
=> Fix cosipbft issue

core/ordering/cosipbft/mod_test.go, mod.go
Also: increase round timeout because of slow machines.
=> Disable logging and allow to set the level with an env variable

cli/node/memcoin/mod_test.go, core/ordering/cosipbft/blocksync/default.go, core/ordering/cosipbft/blocksync/default_test.go, core/ordering/cosipbft/controller/mod.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, cosi/flatcosi/mod.go, cosi/mod.go, cosi/threshold/actor.go, cosi/threshold/actor_test.go, cosi/threshold/handler_test.go, cosi/threshold/json/mod.go, cosi/threshold/json/mod_test.go, cosi/threshold/mod.go, cosi/threshold/mod_test.go, cosi/threshold/types/mod.go, cosi/threshold/types/mod_test.go, internal/testing/fake/mod.go, mino/gossip/flat.go, mino/gossip/flat_test.go, serde/json/mod.go
This switches from the flat collective signing to a threshold one for the integration tests.
=> Core: use a thresholded collective signing

core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/ordering/cosipbft/pbft/mod.go
This changes the behavior to use a different timeout after a view change happened. This is mainly for unit testing to work with slow machines but it also makes sense in production deployment.
=> Cosipbft: use a different timeout after a failure

core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go
An issue was included with #119 as the new leader was using the old
small timeout. This is now fixed.
=> Fix test after merges

mino/minogrpc/mod_test.go
This fixes a test where the instance is closed before it actually started
which is producing an error on gRPC side.
=> Fix minogrpc test

core/execution/baremetal/mod.go, core/execution/baremetal/mod_test.go, core/execution/baremetal/viewchange/mod.go, core/execution/baremetal/viewchange/mod_test.go, core/execution/mod.go, core/ordering/cosipbft/mod_test.go, core/ordering/cosipbft/pbft/mod_test.go, core/ordering/pow/mod_test.go, core/txn/pool/gossip/mod_test.go, core/validation/simple/mod.go, core/validation/simple/mod_test.go
This improves the execution service to include previous transactions
so that view change can make sure only one is accepted per block.
=> ViewChange: check only one tx per block

core/ordering/cosipbft/blockstore/mem.go, core/ordering/cosipbft/blockstore/mem_test.go, core/ordering/cosipbft/blockstore/mod.go, core/ordering/cosipbft/blockstore/tree.go, core/ordering/cosipbft/blockstore/tree_test.go, core/ordering/cosipbft/blocksync/default.go, core/ordering/cosipbft/blocksync/default_test.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/ordering/cosipbft/pbft/mod.go, core/ordering/cosipbft/proc.go, internal/testing/fake/mino.go, internal/testing/fake/mod.go, mino/minoch/rpc.go, mino/minoch/rpc_test.go
This fixes a synchronization issue between the tree and the latest block which is failing the test from time to time.
Also: improve blocksync
=> Cosipbft: fix a synchronization issue with the tree

cli/node/builder.go, cli/node/builder_test.go, cli/node/daemon.go, cli/node/daemon_test.go, cli/node/memcoin/mod.go, cli/node/memcoin/mod_test.go
Because the tests were listening for the terminate signal, that was causing some instability. It now only waits for the channel to be closed in the test, and listen for the signal in production.
=> Memcoin: fix signal issues with Windows during tests

core/ordering/cosipbft/blockstore/disk.go, core/ordering/cosipbft/blockstore/mem.go, core/ordering/cosipbft/blockstore/mem_test.go
This changes the observer to not drop events when the channel is busy
but fill a buffer that will deliver the events in order progressively.
=> Blockstore: use a buffer for watch events

Makefile
The command refreshes the documentation on pkg.go.dev by forcing the proxy to get the latest master commit.
=> Make: add a command to update the doc

core/ordering/cosipbft/blocksync/default.go, core/ordering/cosipbft/blocksync/default_test.go, core/ordering/cosipbft/controller/mod.go, core/ordering/cosipbft/controller/mod_test.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, cosi/flatcosi/mod.go, cosi/flatcosi/mod_test.go, cosi/threshold/mod.go, cosi/threshold/mod_test.go, dkg/pedersen/mod.go, dkg/pedersen/mod_test.go, internal/testing/fake/mino.go, mino/gossip/flat.go, mino/gossip/flat_test.go, mino/minoch/example_test.go, mino/minoch/mod.go, mino/minoch/mod_test.go, mino/minoch/rpc_test.go, mino/minogrpc/example_test.go, mino/minogrpc/mod.go, mino/minogrpc/mod_test.go, mino/minogrpc/server_test.go, mino/mod.go, mino/mod_test.go
This changes the way namespaces are defined. It now considers the namespace as something that already exists and you simply access it and it renames namespace to segment.
=> Mino: namespace refactoring

serde/example_test.go, serde/mod.go, serde/xml/mod.go, serde/xml/mod_test.go
This demonstrates how different formats can be used by simply switching the context.
Needs #143
=> Serde: add XML to the example

mino/minogrpc/mod.go, mino/minogrpc/mod_test.go, mino/minogrpc/server.go, mino/minogrpc/server_test.go
Required to exchange certificates when creating multiple nodes in a containerised environment with each container having a unique IP rather than `127.0.0.1`
=> minogrpc: use node's IP while creating certificate

mino/minogrpc/example_test.go, mino/minogrpc/rpc.go, mino/minogrpc/rpc_test.go, mino/minogrpc/server.go, mino/router/mod.go, mino/router/tree/example_test.go, mino/router/tree/mod.go, mino/router/tree/mod_test.go
Some routing protocols require the router to know the node's address in order to decide the route.
This PR updates `Router.New` to accept the node's address. The `tree` router isn't changed since it doesn't make use of this information.
=> Router: Accept node's address

.gitignore, contracts/access/controller/action.go, contracts/access/controller/action_test.go, contracts/access/controller/jstore.go, contracts/access/controller/jstore_test.go, contracts/access/controller/mod.go, contracts/access/controller/mod_test.go, contracts/access/mod.go, contracts/access/mod_test.go
Adds an access contract that allows an authorized identity to grant access on the other smart contracts. Each node must locally grant access to the identity that can use this smart contract, with the cli, in the form:
```
memcoin [--config /tmp/node1] access add [--identity IDENTITY ...]
```
As this access is critical and can be different on each node, it is kept in a separate storage on each server and not part of the blockchain.
=> Adds the access contract

core/execution/benchmark/mod_test.go, core/execution/tcp/mod.go
Changes the order of parsing tcp endpoint to:
1. The argument passed in `step`
2. The environment variable `UNIKERNEL_TCP`
3. Defaulting to `defaultUnikernelAddr`
=> TCP execution: change order of parsing addr

core/execution/benchmark/Report.md
We can ignore the checks since `unikernel-initial` is still WIP. 
[Report.pdf](https://github.com/dedis/dela/files/6675467/Report.pdf)
=> Add WASM results to the technical report

test/cosidela_test.go, test/integration_test.go
A misuse of the mino interface prevented the use of a port 0. In fact a node's address should be retrieved with the mino interface.
closes #196
=> Allows port 0 in integration test

core/ordering/cosipbft/pbft/mod.go, mino/proxy/http/controller/action.go, mino/proxy/http/controller/action_test.go, mino/proxy/http/controller/mod.go, mod.go
Changed the way we use Prometheus: Dela exposes the collectors it defines, and it is left to the developper to register them, or not. Like so, a foreign application can use its existing Prometheus registry and simply add the Dela metrics.
=> Exposes Prometheus collectors

mino/minogrpc/controller/actions.go, mino/minogrpc/controller/actions_test.go, mino/minogrpc/controller/mod.go, mino/minogrpc/controller/mod_test.go
Sometimes we need to remove an existing certificate from a node. This PR adds a `memcoin minogrpc certificates rm --address <addr>` CLI command to do that.
This is especially convenient when we need to regenerate a node's certificate, for example when its public address has changed.
=> Adds an action to delete certificates

core/ordering/cosipbft/mod.go, core/ordering/cosipbft/pbft/mod.go, core/ordering/cosipbft/pbft/mod_test.go
- updates `calculateThreshold` to handle the case where `f` is zero.
Close #214
=> Updates PBFT to allow a leader catchup

mino/minogrpc/controller/mod.go, mino/minogrpc/controller/mod_test.go, mino/router/flat/json/mod.go, mino/router/flat/json/mod_test.go, mino/router/flat/mod.go, mino/router/flat/mod_test.go, mino/router/flat/types/handshake.go, mino/router/flat/types/handshake_test.go, mino/router/flat/types/mod.go, mino/router/flat/types/packet.go, mino/router/flat/types/packet_test.go, mino/router/mod.go, serde/json/mod.go
This flat routing implementation assumes a N-N connectivity among nodes. It brings more stability on a small topology, as failing tree nodes can break communications.
This is basically a simplified copy of the tree routing implementation.
Also updates `memcoin` to use by default the flat routing. A new flag `routing` can specify either `flat` (default) or `tree`.
=> Adds a flat routing implementation

mino/minogrpc/mod.go, mino/minogrpc/server.go
The server would not use the certificate's private key if specified. Which makes the TLS handshake fail.
=> Fixes wrong certificate key used

internal/testing/fake/tracing.go, mino/minogrpc/controller/actions_test.go, mino/minogrpc/controller/mod.go, mino/minogrpc/controller/mod_test.go, mino/minogrpc/mod.go, mino/minogrpc/mod_test.go, mino/minogrpc/server.go, mino/minogrpc/server_test.go
Adds an option to disable TLS on gRPCs connections. This is only useful for testing purposes or when the node is behind a reverse-proxy.
=> Adds insecure mode on minogrpc

core/ordering/cosipbft/blockstore/disk.go, core/ordering/cosipbft/blockstore/disk_test.go, core/ordering/cosipbft/blocksync/default.go, core/ordering/cosipbft/blocksync/default_test.go, core/ordering/cosipbft/controller/mod.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/ordering/cosipbft/pbft/mod.go, core/ordering/cosipbft/proof.go, core/ordering/cosipbft/proof_test.go, core/ordering/cosipbft/types/chain.go, core/ordering/cosipbft/types/chain_test.go, core/ordering/cosipbft/types/mod.go, test/cosidela_test.go, test/integration_test.go
- The chain verification verifies only from a given Digest, in case we trust blocks already stored
- GetProof will get links up to the last one, instead of blocklinks, sparing blocks unmarshalling and verification
Fix https://github.com/dedis/dela/issues/238
=> Optimizes some verification operations

.github/workflows/go_test.yml
putting the test without coverage first allows to see the failed tests verbosely.
=> test without coverage first to see failed tests

dkg/pedersen/dkg.go
The unintended behavior was introduced in ddb238b305d6cc05c7a92d7d5c049904488a65a3. After discussion on Slack, we concluded that this was a mistake and the correct behavior was to align with what the rest of the code thinks the threshold is.
=> dkg start: honor `threshold` parameter

contracts/value/value.go, contracts/value/value_test.go, test/integration_test.go
There's a weakness in Dela (#258) whereby the (existing) smart contracts store key=values without any prefix for the keys in a shared key/value store. Effectively this would allow any malicious user to overwrite other smart contracts' data.
This fixes it for the `value` contract.
We probably need to do something similar for https://github.com/dedis/d-voting
@PascalinDe @lanterno for your information, the current key/value store is limited to keys of 32 bytes. Do reach out if adding a prefix could be a problem for D-Voting (we haven't checked).
=> Added prefix for value contract storage

contracts/value/value_test.go, core/access/darc/darc.go, core/access/darc/darc_test.go, core/store/prefixed/prefixed.go, core/store/store.go, testing/fake/store.go
Some tests were becoming hard to write with the super-simple fake `InMemorySnapshot`.
This should make things easier, but carries the risk of breaking things.
This draft PR was created to let the CI scream at us while we proceed with other developments.
=> More realistic fake.InMemorySnapshot

.editorconfig, contracts/access/access.go, contracts/access/access_test.go, contracts/access/controller/action.go, contracts/access/controller/controller.go, contracts/value/controller/controller.go, contracts/value/value.go, contracts/value/value_test.go, core/access/darc/darc.go, core/access/darc/darc_test.go, core/execution/native/example_test.go, core/execution/native/native.go, core/execution/native/native_test.go, core/ordering/cosipbft/contracts/viewchange/viewchange.go, core/ordering/cosipbft/contracts/viewchange/viewchange_test.go, core/ordering/cosipbft/controller/controller.go, core/ordering/cosipbft/cosipbft.go, core/ordering/cosipbft/cosipbft_test.go, core/ordering/cosipbft/proc.go, core/ordering/pow/pow_test.go, core/store/prefixed/prefixed.go, core/validation/simple/example_test.go, test/cosidela_test.go, test/integration_test.go, testing/fake/store.go
There's a weakness in Dela (https://github.com/dedis/dela/issues/258) whereby the (existing) smart contracts store key=values without any prefix for the keys in a shared key/value store. Effectively this would allow any malicious user to overwrite other smart contracts' data.
This fixes it for the Distributed Access Rights Controls (DARC) functionality.
=> Added prefix for DARC storage
