.travis.yml
Setup Travis with coverage to help the early stages.
=> Setup Travis + coverage

Makefile, README.md, blockchain/skipchain/messages.pb.go, consensus/cosipbft/forward_link.go, consensus/cosipbft/forward_link_test.go, consensus/cosipbft/messages.pb.go, consensus/cosipbft/mod.go, consensus/cosipbft/mod_test.go, consensus/cosipbft/queue.go, consensus/cosipbft/queue_test.go, cosi/blscosi/messages.pb.go, crypto/bls/messages.pb.go, crypto/mod.go, go.mod, go.sum, mino/minogrpc/overlay.pb.go
This adds a hash factory to not rely on a single hash algorithm and improve unit tests further.
=> Hash module

blockchain/mod.go, blockchain/skipchain/block.go, blockchain/skipchain/block_test.go, blockchain/skipchain/handler.go, blockchain/skipchain/member.go, blockchain/skipchain/mod.go, blockchain/skipchain/mod_test.go, consensus/cosipbft/forward_link.go, consensus/cosipbft/forward_link_test.go, consensus/cosipbft/messages.pb.go, consensus/cosipbft/messages.proto, consensus/cosipbft/mod.go, consensus/cosipbft/mod_test.go, consensus/cosipbft/queue.go, consensus/cosipbft/queue_test.go, consensus/cosipbft/requests.go, consensus/mod.go, cosi/blscosi/mod.go, cosi/mod.go, crypto/bls/mod.go, crypto/mod.go, mino/minoch/manager.go, mino/minoch/rpc.go, mino/minoch/rpc_test.go, mino/minogrpc/server.go, mino/minogrpc/server_test.go, mino/mod.go
This refactors the cosi interface so that it can verify the signatures during the protocol. The actual unit tests will come after this PR.
=> Refactor cosi interface

blockchain/mod.go, blockchain/skipchain/mod.go, blockchain/skipchain/mod_test.go, consensus/cosipbft/mod.go, consensus/cosipbft/mod_test.go, consensus/mod.go
Use actors all the way to blockchain to make sure the modules are listening before usage.
=> Actorify the consensus to follow cosi

consensus/cosipbft/mod.go, consensus/cosipbft/mod_test.go, consensus/mod.go, consensus/qsc/broadcast.go, consensus/qsc/mod.go, consensus/qsc/mod_test.go
This PR adds a close function to consensus actors to abort execution.
=> Close consensus executions

blockchain/skipchain/mod.go, blockchain/skipchain/validator.go, blockchain/skipchain/validator_test.go, consensus/qsc/mod.go, consensus/qsc/mod_test.go
Skipchain now supports multiple block proposals.
Also: fix one QSC test coverage.
=> Skipchain validator buffer

blockchain/mod.go, blockchain/skipchain/mod.go, blockchain/skipchain/mod_test.go, blockchain/skipchain/validator.go, blockchain/skipchain/validator_test.go, blockchain/watcher_test.go
Implements the watch function for skipchain.
Also: unit tests for the blockchain watcher.
=> Skipchain watch

blockchain/skipchain/mod.go, blockchain/skipchain/mod_test.go, crypto/mod.go, crypto/rand.go, crypto/rand_test.go
This adds a random generator interface to the crypto module and uses it in skipchain.
=> Skipchain: use the crypto rand interface

blockchain/skipchain/db.go, blockchain/skipchain/db_test.go, blockchain/skipchain/handler.go, blockchain/skipchain/handler_test.go, blockchain/skipchain/mod.go, blockchain/skipchain/validator_test.go, docs/introduction.md, ledger/byzcoin/mod.go, ledger/byzcoin/txproc.go, ledger/byzcoin/txproc_test.go, ledger/inventory/mem/mod.go, ledger/inventory/mod.go
This changes the skipchain module to process the initial payload of the genesis block.
=> Skipchain genesis processing

docs/introduction.md
Add missing terminologies to the documentation.
=> Doc terminologies

mino/minoch/manager.go, mino/minoch/manager_test.go, mino/minoch/mod.go, mino/minoch/mod_test.go, mino/minoch/rpc.go, mino/minoch/rpc_test.go, mino/mod.go
It improves the minoch package to reflect recent changes.
=> Minoch: extend coverage of unit tests

core/tap/anon/json/mod.go, core/tap/anon/json/mod_test.go, core/tap/anon/mod.go, core/tap/anon/mod_test.go, core/tap/mod.go, core/tap/pool/gossip/mod.go, core/tap/pool/gossip/mod_test.go, core/tap/pool/mem/mod.go, core/tap/pool/mem/mod_test.go, core/tap/pool/mod.go, serde/json/mod.go
=> Core pool gossip

blockchain/skipchain/reactor_test.go, core/ordering/cosipbft/blockstore/mem.go, core/ordering/cosipbft/blockstore/mem_test.go, core/ordering/cosipbft/blockstore/mod.go, core/ordering/cosipbft/blockstore/tree.go, core/ordering/cosipbft/blockstore/tree_test.go, core/ordering/cosipbft/blocksync/default.go, core/ordering/cosipbft/blocksync/default_test.go, core/ordering/cosipbft/blocksync/json/mod.go, core/ordering/cosipbft/blocksync/json/mod_test.go, core/ordering/cosipbft/blocksync/mod.go, core/ordering/cosipbft/blocksync/types/mod.go, core/ordering/cosipbft/blocksync/types/mod_test.go, core/ordering/cosipbft/json/link.go, core/ordering/cosipbft/json/mod.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/ordering/cosipbft/pbft/mod.go, core/ordering/cosipbft/pbft/mod_test.go, core/ordering/cosipbft/proc.go, core/ordering/cosipbft/proc_test.go, core/ordering/cosipbft/types/block.go, core/ordering/cosipbft/types/block_test.go, core/ordering/cosipbft/types/messages.go, core/ordering/cosipbft/types/mod.go, dkg/pedersen/handler_test.go, dkg/pedersen/mod_test.go, internal/testing/fake/mod.go, serde/json/mod.go
=> CosiPBFT synchronization of blocks

core/ordering/cosipbft/blocksync/default.go, core/ordering/cosipbft/blocksync/default_test.go, core/ordering/cosipbft/blocksync/mod.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/ordering/cosipbft/proc_test.go
=> Make synchronizer easier to use

core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/ordering/pow/mod.go, core/txn/pool/gatherer.go, core/txn/pool/gatherer_test.go, core/txn/pool/gossip/mod.go, core/txn/pool/gossip/mod_test.go, core/txn/pool/mem/mod.go, core/txn/pool/mem/mod_test.go, core/txn/pool/mod.go
=> Make transaction pool easier to use

core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/store/kv/default.go, core/store/kv/default_test.go, core/store/kv/mod.go, core/txn/pool/gatherer.go, core/txn/pool/gatherer_test.go, core/txn/pool/gossip/mod.go, core/txn/pool/gossip/mod_test.go, core/txn/pool/mem/mod.go, core/txn/pool/mem/mod_test.go
This improve the close function of the cosipbft ordering service so that it waits for the round to finish (or fail).
Needs #86
=> Graceful close of the ordering service

core/ordering/cosipbft/blockstore/mem.go, core/ordering/cosipbft/blockstore/mem_test.go, core/ordering/cosipbft/blockstore/mod.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/ordering/cosipbft/pbft/mod.go, core/ordering/cosipbft/pbft/mod_test.go, core/ordering/cosipbft/proc.go, core/ordering/cosipbft/proc_test.go, core/store/hashtree/binprefix/disk.go, core/store/hashtree/binprefix/disk_test.go, core/store/hashtree/binprefix/mod.go, core/store/hashtree/binprefix/mod_test.go, core/store/hashtree/binprefix/tree_test.go, core/store/hashtree/mod.go, core/store/kv/default.go, core/store/kv/default_test.go, core/store/kv/mod.go, core/store/mod.go
=> Core: use db transaction when required

core/ordering/cosipbft/blockstore/genesis.go, core/ordering/cosipbft/blockstore/genesis_test.go, core/ordering/cosipbft/blockstore/mod.go, core/ordering/cosipbft/blocksync/default_test.go, core/ordering/cosipbft/json/chain.go, core/ordering/cosipbft/json/chain_test.go, core/ordering/cosipbft/json/link.go, core/ordering/cosipbft/json/link_test.go, core/ordering/cosipbft/json/mod.go, core/ordering/cosipbft/json/mod_test.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/ordering/cosipbft/proc.go, core/ordering/cosipbft/proc_test.go, core/ordering/cosipbft/proof_test.go, core/ordering/cosipbft/types/block.go, core/ordering/cosipbft/types/block_test.go, core/ordering/cosipbft/types/chain_test.go
This adds the missing for the JSON format.
=> Core: json format tests for cosipbft

crypto/bls/json/mod.go, crypto/bls/json/mod_test.go
=> Crypto: fix a todo in bls

cosi/threshold/signature.go, cosi/threshold/signature_test.go, internal/testing/fake/mod.go
This fixes a todo in the cosi package.
=> Cosi: fix a todo in threshold

cli/node/memcoin/mod.go, core/store/hashtree/binprefix/mod.go, core/store/hashtree/binprefix/tree.go, core/txn/signed/mod.go, internal/mcheck/mod.go, internal/mcheck/mod_test.go, internal/mcheck/testdata/src/comment/mod1.go, internal/mcheck/testdata/src/ifcheck/mod2.go
Ignores comments that start with a URL.
=> Adds minor updates on mcheck

dkg/pedersen/mod_test.go, mino/minogrpc/addr.go, mino/minogrpc/addr_test.go, mino/minogrpc/controller/mod.go, mino/minogrpc/mod.go, mino/minogrpc/mod_test.go, mino/minogrpc/server_test.go
=> Minogrpc: allow port 0

mino/minogrpc/rpc.go, mino/minogrpc/server.go, mino/minogrpc/server_test.go, mino/minogrpc/session/mod.go, mino/minogrpc/session/mod_test.go
=> Minogrpc: session with multiple parents

cli/node/memcoin/mod_test.go, core/ordering/cosipbft/blockstore/disk.go, core/ordering/cosipbft/blockstore/disk_test.go, core/ordering/cosipbft/blockstore/genesis.go, core/ordering/cosipbft/blockstore/genesis_test.go, core/ordering/cosipbft/blockstore/mem_test.go, core/ordering/cosipbft/blocksync/default.go, core/ordering/cosipbft/blocksync/default_test.go, core/ordering/cosipbft/controller/mod.go, core/ordering/cosipbft/controller/mod_test.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/ordering/cosipbft/pbft/mod.go, core/ordering/cosipbft/pbft/mod_test.go, core/ordering/cosipbft/proc.go, core/store/hashtree/binprefix/disk.go, core/store/hashtree/binprefix/disk_test.go, core/store/hashtree/binprefix/mod.go, core/store/hashtree/binprefix/mod_test.go, core/store/hashtree/binprefix/path.go, core/store/hashtree/binprefix/path_test.go, core/store/hashtree/binprefix/tree.go, core/store/hashtree/binprefix/tree_test.go, crypto/bls/mod.go, crypto/bls/mod_test.go, mino/minoch/rpc.go, mino/minogrpc/rpc.go, mino/minogrpc/server.go, mino/minogrpc/server_test.go
Also: change the block index logic to start at 0 instead of assuming the genesis block is the zero index.
=> Core: persistent stores

core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, internal/testing/fake/mod.go
This changes the behaviour of the main loop so that it keeps trying the round instead of completely failing.
=> Cosipbft: backoff on failure but keep running

cli/node/builder.go, cli/node/builder_test.go, cli/node/daemon_test.go, cli/node/memcoin/mod_test.go, cli/node/mod.go, core/ordering/cosipbft/controller/action_test.go, core/ordering/cosipbft/controller/mod.go, core/ordering/cosipbft/controller/mod_test.go, core/ordering/cosipbft/mod.go, core/ordering/mod.go, core/store/hashtree/binprefix/tree.go, core/txn/pool/gatherer.go, core/txn/pool/gossip/mod.go, core/txn/pool/gossip/mod_test.go, core/txn/pool/mem/mod.go, core/txn/pool/mod.go, core/txn/signed/controller/mod.go, dkg/pedersen/controller/mod.go, dkg/pedersen/controller/mod_test.go, mino/minogrpc/controller/mod.go, mino/minogrpc/controller/mod_test.go, mino/proxy/http/controller/mod.go, mino/proxy/http/controller/mod_test.go
=> CLI: adds a stop routine to initializers

core/ordering/cosipbft/controller/action_test.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/txn/mod.go, core/txn/pool/gatherer.go, core/txn/pool/gatherer_test.go, core/txn/pool/gossip/mod.go, core/txn/pool/gossip/mod_test.go, core/txn/pool/mem/mod.go, core/txn/pool/mem/mod_test.go, core/txn/pool/mod.go, core/txn/signed/controller/mod.go, core/validation/mod.go, core/validation/simple/mod.go, core/validation/simple/mod_test.go
This improves the memory management of the transaction pool as the history was growing without any limit. It now uses a filter to get rid of invalid transactions.
=> Pool: improve memory management

cli/node/memcoin/mod.go, cli/node/memcoin/mod_test.go, core/ordering/cosipbft/controller/mod.go, core/ordering/cosipbft/controller/mod_test.go, core/store/hashtree/binprefix/tree_test.go, core/store/kv/controller/mod.go, core/store/kv/default_test.go, crypto/loader/file.go, crypto/loader/file_test.go, crypto/loader/mod.go, internal/testing/fake/mino.go, internal/testing/fake/store.go, mino/minogrpc/certs/disk.go, mino/minogrpc/certs/disk_test.go, mino/minogrpc/certs/mem.go, mino/minogrpc/certs/mem_test.go, mino/minogrpc/certs/mod.go, mino/minogrpc/controller/actions_test.go, mino/minogrpc/controller/mod.go, mino/minogrpc/controller/mod_test.go, mino/minogrpc/mod.go, mino/minogrpc/mod_test.go, mino/minogrpc/rpc.go, mino/minogrpc/rpc_test.go, mino/minogrpc/server.go, mino/minogrpc/server_test.go
This implements a persistent storage for the certificates.
Also: store the certificate private key to the disk.
=> Minogrpc: certificates storage on disk

cosi/flatcosi/example_test.go, cosi/flatcosi/handler.go, cosi/flatcosi/handler_test.go, cosi/flatcosi/mod.go, cosi/flatcosi/mod_test.go, cosi/mod.go
This adds technical documentation to the code, as well as examples.
=> Documentation: update flatcosi comments, add example.

core/ordering/cosipbft/blocksync/default_test.go, core/ordering/cosipbft/controller/mod.go, core/ordering/cosipbft/mod_test.go, cosi/messages.go, cosi/threshold/actor.go, cosi/threshold/actor_test.go, cosi/threshold/handler.go, cosi/threshold/handler_test.go, cosi/threshold/mod.go, cosi/threshold/mod_test.go, cosi/threshold/types/mod.go, dkg/pedersen/handler_test.go, dkg/pedersen/mod_test.go, internal/testing/fake/mino.go
This add the technical documentation to the threshold collective signing.
Also: clean some of the tests
=> Documentation: thresholded collective signing documentation

cli/node/memcoin/mod_test.go, core/ordering/cosipbft/mod_test.go, crypto/bls/example_test.go, crypto/common/example_test.go, crypto/common/mod.go, crypto/common/mod_test.go, crypto/ed25519/example_test.go, crypto/loader/example_test.go, crypto/loader/file.go, crypto/loader/mod.go
Also: update comment for the loader
=> Documentation: add examples to crypto packages

core/ordering/cosipbft/controller/action.go, core/ordering/cosipbft/controller/action_test.go, mino/minogrpc/mod.go, mino/minogrpc/mod_test.go, mino/minogrpc/rpc.go, mino/minogrpc/rpc_test.go, mino/minogrpc/server.go, mino/minogrpc/server_test.go
Also: fix events watch in controller to be before the tx is sent
=> Documentation: update minogrpc documentation

mino/minogrpc/certs/disk.go, mino/minogrpc/certs/example_test.go, mino/minogrpc/certs/mem.go, mino/minogrpc/certs/mod.go, mino/minogrpc/controller/actions.go, mino/minogrpc/controller/mod.go, mino/minogrpc/example_test.go, mino/minogrpc/session/addr.go, mino/minogrpc/session/mod.go, mino/minogrpc/session/queue.go, mino/minogrpc/tokens/mod.go
=> Documentation: update minogrpc packages

cli/node/builder.go, cli/node/builder_test.go, cli/node/daemon.go, cli/node/daemon_test.go, cli/node/memcoin/mod_test.go, core/ordering/cosipbft/mod.go
This improves the communication between a client and the daemon so that error are detected as such and make the command fails. This should improve the connection with the daemon under Windows.
=> Fix: daemon socket communication

core/ordering/cosipbft/pbft/mod.go, core/ordering/cosipbft/pbft/mod_test.go, core/ordering/cosipbft/pbft/view.go
=> Documentation: update pbft comments

core/ordering/cosipbft/blockstore/disk_test.go, core/ordering/cosipbft/blockstore/mem_test.go, core/ordering/cosipbft/blocksync/default_test.go, core/ordering/cosipbft/blocksync/types/mod_test.go, core/ordering/cosipbft/json/link_test.go, core/ordering/cosipbft/json/mod.go, core/ordering/cosipbft/json/mod_test.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/mod_test.go, core/ordering/cosipbft/pbft/mod_test.go, core/ordering/cosipbft/proc_test.go, core/ordering/cosipbft/proof_test.go, core/ordering/cosipbft/types/block.go, core/ordering/cosipbft/types/block_test.go, core/ordering/pow/block.go, core/ordering/pow/block_test.go, core/ordering/pow/mod.go, core/ordering/pow/mod_test.go, core/validation/mod.go, core/validation/simple/example_test.go, core/validation/simple/json/mod.go, core/validation/simple/mod.go, core/validation/simple/mod_test.go, core/validation/simple/result.go, core/validation/simple/result_test.go, core/watcher.go
=> Documentation: update validation comments + example

cli/node/daemon_test.go, cli/node/flagset.go
Checks for float flags and convert them back to int if possible. Updates the test.
fixes #163
=> Fixes wrong marshalling of int flags

core/ordering/cosipbft/blocksync/default.go, core/ordering/cosipbft/contracts/viewchange/mod.go, core/ordering/cosipbft/mod.go, core/ordering/cosipbft/pbft/mod.go, core/txn/pool/controller/action.go, core/txn/pool/controller/action_test.go, core/txn/pool/controller/mod.go, core/txn/pool/controller/mod_test.go, core/txn/signed/mod.go, core/validation/simple/example_test.go, core/validation/simple/mod.go, crypto/loader/file.go, crypto/loader/file_test.go, crypto/loader/mod.go
This PR add a controller to the pool, which allows one to send transactions to the pool.
The new command is of form:
```
memcoin [--config CONFIG] pool add --key KEY [{--args KEY --args VALUE} ...] [--nonce NONCE]
=> Adds a pool controller

core/execution/benchmark/Report.md
[Report.pdf](https://github.com/dedis/dela/files/6466245/Report.pdf)
=> Adds a technical report

mino/minogrpc/server.go
=> Updates minimum version required for TLS

go.mod, go.sum, mino/minogrpc/certs/mem.go, mino/minogrpc/mod.go, mino/minogrpc/server.go
=> Updates server TLS minimum certificate

.gitignore, dkg/pedersen/controller/action.go, dkg/pedersen/controller/mod.go, dkg/pedersen/controller/mod_test.go, dkg/pedersen/dkgcli/README.md, dkg/pedersen/dkgcli/dockerfile, dkg/pedersen/dkgcli/mod.go, mino/minogrpc/controller/mod.go
Adds a `dkgcli` utility tool. Allows one to do the initialization and setup of DKG.
=> Adds a CLI utility for DKG

go.mod, go.sum, mod.go
Now able to log to a file whenever LOGF="myfile.log" preceeds the application (memcoin, dkgcli, ...)
=> log to given file as well

internal/testing/fake/store.go, mino/minogrpc/controller/mod_test.go
This is a candidate fix as it's hard to reproduce locally on my Mac, I'll be using the CI to verify.
Fixes #249
=> Fix panic in TestMiniController_FailMarshalKey_OnStart

crypto/bls/bls.go, crypto/bls/bls_test.go
Simply an accessor. This would help with the DKG for F3B-IBE.
=> add bls PublicKey GetPoint

dkg/dkg.go, dkg/pedersen/controller/action.go, dkg/pedersen/controller/action_test.go, dkg/pedersen/controller/controller.go, dkg/pedersen/dkg.go, dkg/pedersen/json/json.go, dkg/pedersen/json/json_test.go, dkg/pedersen/ocs.go, dkg/pedersen/pedersen.go, dkg/pedersen/pedersen_test.go, dkg/pedersen/reencrypt.go, dkg/pedersen/resharing_test.go, dkg/pedersen/types/messages.go, dkg/pedersen/types/messages_test.go, test/testcreatekey.sh
- cleaned up the Actor interface to just keep the reencrypt.
- added a shell interface to be able to reencrypt a message through the CLI.
=> Reencrypt cli

dkg/pedersen/controller/action.go, dkg/pedersen/pedersen.go, dkg/pedersen/pedersen_test.go, dkg/pedersen/reencrypt.go
fixed the threshold issue for re-encryption
=> Reencrypt cli2

.github/workflows/go_test.yml, mino/mino.go
- don't run coverage on forks
- fix one comment
=> Code cleanup
